

function create_debriefing(){
    debrief_time=[];
        
    var deb_block = {
    type: jsPsychHtmlKeyboardResponse,
    stimulus: function() {

        var role = jsPsych.data.get().select('role').values[0];
        if (role=='0'){
        var points_part = jsPsych.data.get().select('fb_trustee_payoff').sum();
        } else if (role=='1'){
        var points_part = jsPsych.data.get().select('fb_trustor_payoff').sum();}

        var tot_earnings = points_part * .01;
        if (tot_earnings>3) {tot_points=300; tot_earnings = 3};

        var type_game = jsPsych.data.get().select('tot_players').values[0];
        if (type_game==1){
            debrief_text = "<p>Thank you for taking part in our study. We would like to provide you with some additional information about the experiment.</p>" +
        "<p>During the game, you were informed that you were playing with other real participants online. This was true, however, in some of the trials you also played with a simulated agent whose behavior was generated by a mathematical model we developed. This was done to ensure that the conditions of the experiment remained consistent for all participants and to better understand people's genuine social behaviors.</p>" +
        "<p>Based on previous research, we know that your behavior would have been very different had you known that you might have played also with simulated agents. In technical terms, this would have constituted a confounding factor that would have undermined the ecological validity of the experiment. In other words, to avoid invalidating your data, we could not disclose that information at the beginning of the experiment.</p>" +        
        "<p>We understand that this may be surprising, and we want to assure you that this procedure is standard practice in research, was developed in accordance with the highest ethical standards, and is purely meant to enable the highest quality and control of experimental variables. Your responses and decisions are valuable and will contribute significantly to our understanding of social behavior.</p>" +
        "<p>If you have any questions or concerns about this aspect of the study, please do not hesitate to contact us. We appreciate your participation and honesty throughout the experiment.</p>"+
        "<p>Thank you once again for your time and contribution.</p>" + 
        "<p>You earned a total of "+String(points_part)+" points and will hence receive a bonus payment of &pound;"+String(tot_earnings)+".</p>"+
        "<p>Press any key to proceed.</p>";
        } else {
            debrief_text = "<p>You earned a total of "+String(points_part)+" points and will hence receive a bonus payment of &pound;"+String(tot_earnings)+".</p>"+
        "<p>Press any key to proceed.</p>";
        }

        return  debrief_text;
    },
    data : {trial: 'performance_fb', task: 'debriefing'},

    on_finish: function(data){
        var role = jsPsych.data.get().select('role').values[0];
        if (role=='0'){
        var points_part = jsPsych.data.get().select('fb_trustee_payoff').sum();
        } else if (role=='1'){
        var points_part = jsPsych.data.get().select('fb_trustor_payoff').sum();}

            data.tot_points = points_part;
            data.exp_dur = jsPsych.data.get().select("time_elapsed").values;
            data.exp_dur = data.exp_dur.slice(-1)[0]; //total time on experiment in milliseconds
            data.subjnum = subjnum;
            data.key_resp = data.response;
            data.response = 999;
    }};

debrief_time.push(deb_block);
return debrief_time
}


